[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
lib_deps = 
    jgromes/RadioLib @ 6.6.0
    olikraus/U8g2 @ ^2.34.2
    h2zero/NimBLE-Arduino @ ^2.1.2